### ISSUE TITLE
Publish 3.0.1 to npm

### ISSUE THREAD

**Issue by timjrobinson** [arj03/ssb-partial-replication#2]
The latest version 2.0.0 on NPM has a different manifest which doesn't have `getFeed` / `getFeedReverse` etc so it doesn't work with [SSB Browser Demo](https://github.com/arj03/ssb-browser-demo/) as it tries to use those functions to download information.

Could you please publish the latest version to npm.

**Comment by arj03** [comment]
Done, thanks @timjrobinson
